<a href="https://colab.research.google.com/github/JeonJeongumggumg/PyTorch/blob/main/Tenser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np

In [11]:
data = [[1, 2],[3, 4]] #데이터로 부터 직접 텐서를 형성(자료형은 자동으로)
x_data = torch.tensor(data)

In [12]:
np_array = np.array(data) #NumPy배열로 형성한 텐서
x_np = torch.from_numpy(np_array)

In [18]:
x_ones = torch.ones_like(x_data) #재정의를 딱히 하지않으면 주어진 인자의 속성을 유지함
print(f"Ones Tensor: \n {x_ones} \n ") # x_data의 속성을 유지

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n ")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 
 
Random Tensor: 
 tensor([[0.2174, 0.8610],
        [0.6710, 0.1094]]) 
 


In [19]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4428, 0.4874, 0.5217],
        [0.2371, 0.9530, 0.3240]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
tensor = torch.rand(4,3)

#텐서의 속성
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([4, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


기본적으로 텐서는 CPU에 생성.

 .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있다.

 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다

In [23]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda") #cuda는 엔비디아의 GPGPU를 활용 할 수 있게 해 주는 소프트웨어 스택

In [25]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}") #첫번째 행 출력
print(f"First column: {tensor[:, 0]}") #첫번째 열 출력
print(f"Last column: {tensor[..., -1]}") #마지막 열 출력
tensor[:,1] = 0 #두번째 열을 0으로 전부 변경
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결가능

torch.cat 과 미묘하게 다른 텐서 결합 연산자(tensor joining operator)인
torch.stack 도 참고

In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [27]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
jimin = tensor.sum() #텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환가능
jimin_item = jimin.item()
print(jimin_item, type(jimin_item))

92.0 <class 'float'>


바꿔치기

원본 텐서가 덮어씌워지므로, 기존 값을 유지하고 싶다면 **tensor + 5**와 같은 연산을 사용해야 합니다.

In [31]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


NumPy 변환(Bridge)

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경

In [32]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [33]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [34]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
